# Generated by Django 6.0.2 on 2026-05-11 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doubts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doubt',
            name='answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doubt',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='doubt',
            name='student',
            field=models.IntegerField(),
        ),
    ]
