# Generated by Django 6.0.2 on 2026-05-13 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doubts', '0003_doubt_answer_alter_doubt_status_alter_doubt_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doubt',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('answered', 'Answered')], default='pending', max_length=20),
        ),
    ]
