# Generated by Django 6.0.2 on 2026-05-13 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doubts', '0004_alter_doubt_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='doubt',
            name='tags',
            field=models.JSONField(default=list),
        ),
    ]
