# Generated by Django 6.0.2 on 2026-05-14 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doubts', '0005_doubt_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='doubt',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='doubt_attachments/'),
        ),
    ]
