# Generated by Django 6.0.2 on 2026-05-14 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doubts', '0007_doubt_resolved_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='doubt',
            name='answer_attachment',
            field=models.FileField(blank=True, null=True, upload_to='answer_attachments/'),
        ),
    ]
