# Generated by Django 6.0.2 on 2026-05-15 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doubts', '0008_doubt_answer_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doubt',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('solved', 'Solved')], default='pending', max_length=20),
        ),
    ]
