# Generated by Django 5.2.14 on 2026-05-19 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doubts', '0010_industry_upgrade'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doubt',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='doubt',
            name='is_overdue',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='doubt',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='doubt',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('solved', 'Solved')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='doubt',
            name='subject',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='doubt',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='doubt',
            name='topic',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
