# Generated by Django 6.0.2 on 2026-05-14 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_mobile_user_roll_number_user_section_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='student_id',
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='year_of_study',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
